package sys.model;
// Generated 24/02/2018 08:37:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Municipios generated by hbm2java
 */
public class Municipios  implements java.io.Serializable {


     private Integer idLocalidad;
     private String municipio;
     private Set<Promotores> promotoreses = new HashSet<Promotores>(0);
     private Set<Personas> personases = new HashSet<Personas>(0);

    public Municipios() {
    }

	
    public Municipios(String municipio) {
        this.municipio = municipio;
    }
    public Municipios(String municipio, Set<Promotores> promotoreses, Set<Personas> personases) {
       this.municipio = municipio;
       this.promotoreses = promotoreses;
       this.personases = personases;
    }
   
    public Integer getIdLocalidad() {
        return this.idLocalidad;
    }
    
    public void setIdLocalidad(Integer idLocalidad) {
        this.idLocalidad = idLocalidad;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public Set<Promotores> getPromotoreses() {
        return this.promotoreses;
    }
    
    public void setPromotoreses(Set<Promotores> promotoreses) {
        this.promotoreses = promotoreses;
    }
    public Set<Personas> getPersonases() {
        return this.personases;
    }
    
    public void setPersonases(Set<Personas> personases) {
        this.personases = personases;
    }




}


