package sys.model;
// Generated 24/02/2018 08:37:37 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Personas generated by hbm2java
 */
public class Personas  implements java.io.Serializable {


     private String curp;
     private Municipios municipios;
     private Promotores promotores;
     private String nombreCompleto;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String direccion;
     private String telefono;
     private String seccion;
     private String claveElectoral;
     private Date fechaNacimineto;

    public Personas() {
        municipios = new Municipios();
        promotores = new Promotores();
    }

    public Personas(String curp, Municipios municipios, Promotores promotores, String nombreCompleto, String apellidoPaterno, String apellidoMaterno, String direccion, String telefono, String seccion, String claveElectoral, Date fechaNacimineto) {
       this.curp = curp;
       this.municipios = municipios;
       this.promotores = promotores;
       this.nombreCompleto = nombreCompleto;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.direccion = direccion;
       this.telefono = telefono;
       this.seccion = seccion;
       this.claveElectoral = claveElectoral;
       this.fechaNacimineto = fechaNacimineto;
    }
   
    public String getCurp() {
        return this.curp;
    }
    
    public void setCurp(String curp) {
        this.curp = curp;
    }
    public Municipios getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Municipios municipios) {
        this.municipios = municipios;
    }
    public Promotores getPromotores() {
        return this.promotores;
    }
    
    public void setPromotores(Promotores promotores) {
        this.promotores = promotores;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(String seccion) {
        this.seccion = seccion;
    }
    public String getClaveElectoral() {
        return this.claveElectoral;
    }
    
    public void setClaveElectoral(String claveElectoral) {
        this.claveElectoral = claveElectoral;
    }
    public Date getFechaNacimineto() {
        return this.fechaNacimineto;
    }
    
    public void setFechaNacimineto(Date fechaNacimineto) {
        this.fechaNacimineto = fechaNacimineto;
    }




}


