package sys.model;
// Generated 24/02/2018 08:37:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Promotores generated by hbm2java
 */
public class Promotores  implements java.io.Serializable {


     private Integer idPromotor;
     private Municipios municipios;
     private String nombreCompleto;
     private Set<Personas> personases = new HashSet<Personas>(0);

    public Promotores() {
        municipios = new Municipios();
    }

	
    public Promotores(Municipios municipios, String nombreCompleto) {
        this.municipios = municipios;
        this.nombreCompleto = nombreCompleto;
    }
    public Promotores(Municipios municipios, String nombreCompleto, Set<Personas> personases) {
       this.municipios = municipios;
       this.nombreCompleto = nombreCompleto;
       this.personases = personases;
    }
   
    public Integer getIdPromotor() {
        return this.idPromotor;
    }
    
    public void setIdPromotor(Integer idPromotor) {
        this.idPromotor = idPromotor;
    }
    public Municipios getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Municipios municipios) {
        this.municipios = municipios;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public Set<Personas> getPersonases() {
        return this.personases;
    }
    
    public void setPersonases(Set<Personas> personases) {
        this.personases = personases;
    }




}


